name: hardware_details
description: A Flutter plugin to retrieve low-level hardware information using native platform APIs.
version: 0.0.5
homepage: https://github.com/mcanevi3/hardware_info
repository: https://github.com/mcanevi3/hardware_info
license: Apache-2.0

environment:
  sdk: ^3.7.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^1.0.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.hardware_details
        pluginClass: HardwareDetailsPlugin
      ios:
        pluginClass: HardwareDetailsPlugin
      macos:
        pluginClass: HardwareDetailsPlugin
      windows:
        pluginClass: HardwareDetailsPluginCApi
      web:
        pluginClass: HardwareDetailsWeb
        fileName: hardware_details_web.dart
